version: 2

sources:
  - name: stackoverflow
    description: "stackoverflow_test_dataset"
    database: bigquery-public-data
    schema: stackoverflow
    tables:
      - name: badges
        description: "stackoverflow_test_table_badges"
